name: mata_vision_aid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.2
  cloud_firestore: ^6.0.0

  # Maps & Location
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.14+2
  geolocator: ^14.0.2

  # Device utilities
  battery_plus: ^7.0.0
  http: ^1.1.0
  image_picker: ^1.2.0

  # UI
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8

  # Tools
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_mata2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo_mata1.png
